train_path: dataset/train.txt
test_path: dataset/test.txt
img_size: 640
batch_size: 16
model: yolov5s
lr: 0.001
lr_step: 20
lr_gamma: 0.1
epochs: 100
save_interval: 10
score_thresh: 0.5
iou_thresh: 0.5

